-- Shopify AI Store Builder intake form (separate from generic leads table)
CREATE TABLE IF NOT EXISTS `shopify_intake_leads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `country` VARCHAR(255) DEFAULT NULL,
  `business_name` VARCHAR(255) DEFAULT NULL,
  `website` VARCHAR(500) DEFAULT NULL,
  `business_description` TEXT,
  `brand_mission` TEXT,
  `problem_solved` TEXT,
  `personality` VARCHAR(50) DEFAULT NULL,
  `categories` TEXT,
  `best_sellers` TEXT,
  `avg_price` VARCHAR(100) DEFAULT NULL,
  `product_physical` TINYINT(1) NOT NULL DEFAULT 0,
  `product_digital` TINYINT(1) NOT NULL DEFAULT 0,
  `product_subscription` TINYINT(1) NOT NULL DEFAULT 0,
  `audience_interests` TEXT,
  `pain_points` TEXT,
  `customer_goals` TEXT,
  `competitor1` VARCHAR(500) DEFAULT NULL,
  `competitor2` VARCHAR(500) DEFAULT NULL,
  `competitor3` VARCHAR(500) DEFAULT NULL,
  `amazon_store` VARCHAR(500) DEFAULT NULL,
  `top_asins` TEXT,
  `amazon_revenue` VARCHAR(100) DEFAULT NULL,
  `notes` TEXT,
  `source_page` VARCHAR(500) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_shopify_intake_created` (`created_at`),
  KEY `idx_shopify_intake_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
